# Site
repository: adrianaMarquez/adrianaMarquez
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Adriana Guadalupe Marquez De la Paz
title: Licenciada en Abogacía
email: delapazlupita20@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: adriana-márquez-190306191



# About Section
about_title: Resumen profesional
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Licenciada titulada de la Universidad de Guadalajara, con conocimientos en las diferentes <mark>áreas de la abogacía (Laboral, administrativa, civil, familiar, penal)</mark>
  capaz de liderar equipos, habilidades de efectivas de comunicación, capacidad de resolución de problemas de conflictos, capacidad de adaptación a las nuevas tecnologías,
  formación continua, actualización de conocimientos día con día, excelente colaboración y comunicación con equipos de trabajo, 
  experiencia con múltiples equipos de trabajo de múltiples sectores comerciales de la industria y 4 años de experiencia con servicio al cliente.
content:
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Universidad de Guadalajara
        link: github.com/adrianaMarquez
        # link_text: Project Website
        additional_links:
          - title:  adrianaMarquez/adrianaMarquez
            icon: fab fa-github
            url: github.com/adrianaMarquez
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          .
        description: | # this will include new lines to allow paragraphs
          Este es uno de los mayores logros de mi vida. Titulo profesional de la Licenciatura de abogacía obtenido en Abril del 2023
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Juzgado segundo de Distrito en Materias Administrativa, Civil y de Trabajo
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Oficial de mantenimiento
        caption: Duración 6 MESES
        quote: >
          Nombramiento de oficial de mantenimiento en el Juzgado Segundo de Distrito en Materias Administrativa, Civil y de Trabajo en el Estado de Jalisco
        description: | # this will include new lines to allow paragraphs
            Acomodar expedientes, en actuaria organizar la correspondencia, oficialía de partes organizar las promociones que presentaban los abogados, también ayudaba a acordar las promociones junto con los auxiliares de los secretarios del juzgado.
      - layout: left
        title: Juzgado Octavo Civil en el Estado de Jalisco
        sub_title: Meritoria
        caption: Duración 1 AÑO
        quote: >
          Meritoria en el Juzgado Octavo Civil en el Estado de Jalisco
        description: | # this will include new lines to allow paragraphs
            Estuve en archivo prestando y acomodo de expedientes, acomodo de las promociones en los expedientes, con las notificadoras y acordando promociones con los auxiliares del juzgado   

      - layout: left
        title: Juzgado Tercero Familiar en el Estado de Jalisco, con sede en Zapopan
        sub_title: Meritoria
        caption: Duración 1 AÑO
        quote: >
          Meritoria en el Juzgado Tercero Familiar en el Estado de Jalisco, con sede en Zapopan.
        description: | # this will include new lines to allow paragraphs
            En archivo prestando, acomodo de expedientes y promociones que presentaban los abogados.         

      - layout: left
        title: Centro de Justicia para las Mujeres
        sub_title: Meritoria
        caption: Duración 3 MESES
        quote: >
          Meritoria en el Centro de Justicia para las Mujeres
        description: | # this will include new lines to allow paragraphs
            Laborando con una auxiliar del ministerio público en el área de Dignidad de las personas amenazas.         
    
      - layout: left
        title: BBVA
        sub_title: Cajera
        caption: Duración 1 AÑO
        quote: >
          Cajera de BBVA en Chapultepec realizando actividades financieras
        description: | # this will include new lines to allow paragraphs
            Cajera de BBVA en Chapultepec realizando actividades financieras, conforme a lo solicitado por los clientes.        
      - layout: left
        title: Despacho laboral 
        sub_title: Abogada
        caption: Duración 1 AÑO
        quote: >
          Despacho laboral realizando actividades relacionadas con amparos desde su elaboración 
        description: | # this will include new lines to allow paragraphs
            Despacho laboral realizando actividades relacionadas con amparos desde su elaboración y presentación de este, transcripción de laudos, agendar citas referentes al proceso laboral, atención personalizada al cliente y a los abogados.        


  - title: Habilidades # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Everyone has skills, but not everyone takes advantage of them.
        quote: >
          Mis habilidades más destacables son:
        description: | # this will include new lines to allow paragraphs
           <mark>Proactiva</mark> , <mark>Liderazgo responsable</mark> , <mark>Comunicación efectiva</mark> , <mark>Sumamente responsable</mark> , <mark>Confidencial</mark>  , <mark>Excelente nivel de ortografía</mark> ,
           <mark>Precaución con los detalles</mark> ,  <mark>Minimalista</mark> ,  <mark>Eficiente</mark> ,  <mark>Audaz</mark> , <mark>Manejo de la paquetería Office</mark> ,  <mark>Adaptabilidad al entorno</mark> ,  
           <mark>Honesta</mark> ,  <mark>Con optimas practicas en la seguridad informática</mark>.
  - title: Certificaciones
    layout: list
    content: 
      - layout: top-middle
        #title: Certifications
        quote: Algunos de mis certificados son
        description: |
         
         -Constancia: en el apoyo logístico, en la conferencia titulada “EL SISTEMA NACIONAL ANTICORRUPCION PARA SERVIDORES PUBLICOS FEDERALES Y ESTATALES” 
         
         -Constancia: en el apoyo logístico, en la conferencia titulada “EL FEDERALISMO ADMINISTRATIVO EN MEXICO”   
        
         -Constancia: por participación en el proyecto de “SEGURIDAD CIUDADANA”
         
         -Constancia: por participación en el “1ER. CONGRESO DE RESPONSABILIDAD MEDICA UTEG”
         
         -Constancia: por participación en las Jornadas Académicas, Jurídicas denominadas “AMPARO Y DERECHOS HUMANOS”
         
         -Constancia: por participación en el programa “CONOCE TU CONGRESO”
         
         -Certificado: por participación del “COMITÉ ORGANIZADO DEL IV FORO ANALITICO Y PROPOSITIVO ACERCA DE LA JUSTICIA EN MEXICO

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
