# Site
repository: isaiasdamian/isaiasdamian
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Isaias Damian Martinez Rivera
title: IT Engineer
email: isaiaschichenol@gmail.com
website: https://github.com/isaiasdamian

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  isaiasdamian
linkedin_username: isaias-damian-martinez-rivera-70333021a



# About Section
about_title: Professional resume
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Active student of the University of Guadalajara with multiple knowledge in the area of Technology, capable of leading teams, communication skills, excellent collaboration and communication with work teams, experience with multiple work teams from multiple business sectors of the industry and 4 years of customer service experience.
  I am most skilled in: <mark>Privacy and data confidentialty</mark> , <mark>Cybersecurity</mark> and <mark>Self learning skills</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Guadalajara
        link: github.com/isaiasdamian
        # link_text: Project Website
        additional_links:
          - title:  isaiasdamian/isaiasdamian
            icon: fab fa-github
            url: github.com/isaiasdamian/isaiasdamian
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest achievements of my life..
        description: | # this will include new lines to allow paragraphs
          Bachelor's Degree in Computer Science: Beginning January 2019, Currently in progress at: University Center for Exact Sciences and Engineering.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FEMSA Company
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Storage Manager
        caption: June 2018 - November 2022
        quote: >
          As a manager I was able to lead teams, deliver satisfactory results, work as a team and meet the needs of customers
        description: | # this will include new lines to allow paragraphs
            I was responsible for the correct operation of the store at night, which had a pleasant performance
      - layout: left
        title: Disc ITBusiness Solutions
        link: https://www.hddisc.com.mx/
        link_text: www.hddisc.com.mx
        sub_title: IT Engineer
        caption: November 2022 - I am currently working for this company

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Everyone has skills, but not everyone takes advantage of them.
        quote: >
          This is probably one of the greatest achievements of my life.
        description: | # this will include new lines to allow paragraphs
          <mark>Knowledge in Agile Software Development</mark> , <mark>Best practices in computer security</mark> , <mark>Management of different Software and Hardware</mark> , <mark>Responsible leadership</mark> and <mark>Proactive</mark> .
  - title: Certifications
    layout: list
    content: 
      - layout: top-middle
        #title: Certifications
        quote: Some of my certificacions are

        description:
         -Diploma from the Jobs program in English, a 900-hour course from Proulex
         -Certification of English in Toefl
         -Certification of English in Pearson
         -Cyber Awareness Certificate
         -Introduction to Cybersecurity by Cisco
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Philosophy
      - Gaming
      - History
      - The universe
      - The sun
      

      One of my idols is Friedrich Nietzsche,  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
